services:
    db-mysql:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        restart: always
        ports:
            - ${DB_PORT}:3306
        volumes:
            - examination-db:/var/lib/mysql
        container_name: examination-system-mysql

    db-redis:
        image: redis:latest
        environment:
            - name=value
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - examination-redis:/data
        container_name: examination-system-redis

volumes:
    examination-db:
    examination-redis:
